---
#####################
# Create the proper databases/user needed
#####################

- name: Database related scripts
  template:
    src: "sql/{{ item }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/azerothcore_sql/"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"
  with_items:
    - "create_databases.sql"
    - "backup.sh"

# Only run this if there is no previous server aka a new install
- name: Create databases, handle users etc.
  shell: mysql < "/home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/azerothcore_sql/create_mysql.sql"
  when: former_build.stat.exists is defined and former_build.stat.exists == false
  become: true

#####################
# Importing SQL
#####################

- name: Assemble and import initial databases
  shell: "bash /home/{{ azerothcore_user }}/{{ azerothcore_source }}/apps/db_assembler/db_assembler.sh 5"
  when: former_build.stat.exists is defined and former_build.stat.exists == false

#####################
# Backup SQL
#####################

- name: Backup databases
  shell: mysqldump {{ item }} | gzip > "/home/{{ azerothcore_user }}/{{ azerothcore_server }}/azerothcore_sql/{{ item }}.sql.gz"
  with_items:
    - "{{ azerothcore_db_auth }}"
    - "{{ azerothcore_db_world }}"
    - "{{ azerothcore_db_characters }}"
  when: former_build.stat.exists is defined and former_build.stat.exists == true
