---
# Is there an old build present
- name: Check if former build is present
  stat:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_server }}"
  register: former_build

# Isn't there a better way? This is not an elegant solution but at best an indicator...
# Compare the old tools with the new - if the same, no updates will be needed. This requires 'bash' and not the default 'sh'
- name: Check if map-tools have been updated
  shell: if [ $(du -c --  /home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/bin/{mmaps_generator,mapextractor,vmap4assembler,vmap4extractor} | tail -n 1 | cut -f1) == $(du -c --  /home/{{ azerothcore_user }}/{{ azerothcore_server }}/server/bin/{mmaps_generator,mapextractor,vmap4assembler,vmap4extractor} | tail -n 1 | cut -f1) ]; then echo 'similar'; else echo 'different'; fi
  args:
    executable: /bin/bash
  register: map_files_diff
  when: former_build.stat.islnk is defined and former_build.stat.islnk

- name: Create server data folder
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/data"
    state: "directory"
    mode: "0755"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"

#####################
# Create new maps
#####################

# Just in case some mess was left behind from earlier...
- name: Clean up previous map related folders
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/{{ item }}"
    state: "absent"
  with_items:
    - Buildings
    - dbc
    - maps
    - mmaps
    - vmaps
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

- name: Information in case new maps have to be created
  debug:
    msg: "New maps etc. will be created, be patient, this will take a while!"
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

# DBC and Maps 
- name: Extract DBC and Maps files
  shell: cd "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/" && /home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/bin/mapextractor
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

# Visual Maps
- name: Extract Visual Maps
  shell: cd "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/" && /home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/bin/vmap4extractor
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

- name: Create Visual Maps folder
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/vmaps"
    state: "directory"
    mode: "0755"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

- name: Assemble Visual Maps
  shell: cd "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/" && /home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/bin/vmap4assembler Buildings vmaps
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

# Movement Maps
- name: Create Movement Maps folder
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/mmaps"
    state: "directory"
    mode: "0755"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

- name: Extract Movement Maps files
  shell: cd "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/" && /home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/bin/mmaps_generator
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

#####################
# Copy new files and cleanup
#####################

# Moving is not supported by modules, so using copy and not shell commands
- name: Copy new map related folders
  copy:
    src: "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/{{ item }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/data/"
    remote_src: "yes"
  with_items:
    - dbc
    - maps
    - mmaps
    - vmaps
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

- name: Clean up new map related folders
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_wow_client }}/{{ item }}"
    state: "absent"
  with_items:
    - Buildings
    - dbc
    - maps
    - mmaps
    - vmaps
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'different' ) or ( former_build.stat.exists is defined and former_build.stat.exists == false )

#####################
# Copy previous maps over since no changes where detected
#####################

- name: Copy old map related folders
  copy:
    src: "/home/{{ azerothcore_user }}/{{ azerothcore_server }}/server/data/{{ item }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_server_release }}/server/data/"
    remote_src: "yes"
  with_items:
    - dbc
    - maps
    - mmaps
    - vmaps
    - vmaps
  when: ( map_files_diff.stdout is defined and map_files_diff.stdout == 'similar' )
